# vless+ws+tlsä¼˜é€‰cfå…¨å±€ä»£ç†é…ç½®
mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
external-controller: :9090

proxies:
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½ä¼˜é€‰
    type: vless
    server: www.visa.com.sg
    port: 443
    uuid: 1111111111111111111111 # UUID
    tls: true
    servername: example.com # ä¼ªè£…åŸŸå
    network: ws
    ws-opts:
      path: /docker # wsè·¯å¾„
      headers:
        Host: example.com # sniåŸŸå
    udp: true

proxy-groups:
  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - ğŸ‡ºğŸ‡¸ ç¾å›½ä¼˜é€‰
      - DIRECT

rules:
  - MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
